[build]
  base = "."
  # 빌드 속도 최적화 (기능 변경 없음)
  command = "npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund && npm run build"
  publish = "apps/app/.next"
  functions = "apps/app/netlify/functions"
  # 변경사항 없으면 빌드 스킵
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "firebase-admin"]

[functions.generate-meal-image]
  timeout = 60

[functions.verify-meal-image]
  timeout = 60

[build.environment]
  NODE_VERSION = "18"
  # 빌드 속도 최적화 환경변수 (기능 변경 없음)
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--prefer-offline --no-audit --no-fund"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정

[functions.auto-generate-meal-images]
  timeout = 60

# API 경로를 Netlify Functions로 리다이렉트
[[redirects]]
  from = "/api/meals"
  to = "/.netlify/functions/meals"
  status = 200
  force = true
