[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  # 모든 함수의 타임아웃을 30초로 설정
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정
[functions.update-meals]
  # 실제 운영 스케줄 (매일 오전 10시에 실행) - 주석 처리
  # schedule = "0 1 * * *" # 매일 한국 시간 오전 10시 (UTC 기준 오전 1시)
  
  # 테스트용 스케줄 (10분 후 실행)
  schedule = "16 12 3 5 *" # UTC 기준 12:16 (2025년 5월 3일), 한국 시간으로는 21:16
  # 현재 한국시간 21:06 → 21:16에 실행

# API 경로를 Netlify Functions로 리다이렉트
[[redirects]]
  from = "/api/meals"
  to = "/.netlify/functions/meals"
  status = 200
  force = true
