[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정
[functions.update-meals]
  # 실제 운영 스케줄 (매일 오전 10시에 실행) - 주석 처리
  # schedule = "0 1 * * *" # 매일 한국 시간 오전 10시 (UTC 기준 오전 1시)
  
  # 테스트용 스케줄 (5분 후 실행)
  schedule = "38 2 * * *" # UTC 기준 02:38 (한국 시간 11:38)
  # 현재 한국시간 11:33 → 11:55에 실행

# Next.js API 라우트 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

# 급식 업데이트 API 엔드포인트 접근 허용
[[redirects]]
  from = "/.netlify/functions/update-meals"
  to = "/.netlify/functions/update-meals"
  status = 200
  force = true
