[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정
[functions.update-meals]
  # 실제 운영 스케줄 (매일 오전 10시에 실행) - 주석 처리
  # schedule = "0 1 * * *" # 매일 한국 시간 오전 10시 (UTC 기준 오전 1시)
  
  # 테스트용 스케줄 (10분 후 실행)
  schedule = "16 12 3 5 *" # UTC 기준 12:16 (2025년 5월 3일), 한국 시간으로는 21:16
  # 현재 한국시간 21:06 → 21:16에 실행

# Next.js API 라우트 리다이렉트 - 기본 설정
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/:splat"
  status = 200
  force = true

# 학교 검색 API 구체적 리다이렉트
[[redirects]]
  from = "/api/schools/*"
  to = "/.netlify/functions/nextjs-server/api/schools/:splat"
  status = 200
  force = true

# 급식 정보 API 구체적 리다이렉트
[[redirects]]
  from = "/api/meals/*"
  to = "/.netlify/functions/nextjs-server/api/meals/:splat"
  status = 200
  force = true

# API 경로를 Netlify Functions로 리다이렉트
[[redirects]]
  from = "/api/meals"
  to = "/.netlify/functions/meals"
  status = 200
  force = true
