[build]
  base = "."
  command = "npm run build"
  publish = "apps/app/.next"
  functions = "apps/app/netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[functions.generate-meal-image]
  background = true

[functions.verify-meal-image]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정
[functions.update-meals]
  # 실제 운영 스케줄 (매일 오전 10시에 실행) - 주석 처리
  # schedule = "0 1 * * *" # 매일 한국 시간 오전 10시 (UTC 기준 오전 1시)
  
  # 매일 오전 9시(한국 시간)에 실행
  schedule = "0 0 * * *" # UTC 기준 0:00, 한국 시간으로는 9:00

# AI 이미지 생성 필요 여부 확인 함수 (12:30에 실행)
[functions.check-missing-meal-images]
  # 실제 운영 스케줄
  schedule = "30 3 * * *" # 매일 UTC 3:30 (한국시간 12:30)

[functions.auto-generate-meal-images]
  background = true
  schedule = "0 5 * * *"

# API 경로를 Netlify Functions로 리다이렉트
[[redirects]]
  from = "/api/meals"
  to = "/.netlify/functions/meals"
  status = 200
  force = true
