[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js API 라우트 리다이렉트
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

# 특정 API 엔드포인트 리다이렉트 제거 - Next.js API 라우트가 처리하도록 함
# Next.js는 src/pages/api/cron/meals.ts 파일을 통해 이 경로를 처리합니다
