[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  # 모든 함수의 설정
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

# 함수 타임아웃 설정
[functions.verify-meal-image]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정
[functions.update-meals]
  # 실제 운영 스케줄 (매일 오전 10시에 실행) - 주석 처리
  # schedule = "0 1 * * *" # 매일 한국 시간 오전 10시 (UTC 기준 오전 1시)
  
  # 테스트용 스케줄 (10분 후 실행)
  schedule = "16 12 3 5 *" # UTC 기준 12:16 (2025년 5월 3일), 한국 시간으로는 21:16
  # 현재 한국시간 21:06 → 21:16에 실행

# AI 이미지 생성 필요 여부 확인 함수 (12:30에 실행)
[functions.check-missing-meal-images]
  # 실제 운영 스케줄
  # schedule = "30 3 * * *" # 매일 UTC 3:30 (한국시간 12:30)
  
  # 테스트용 스케줄 (3분 후 실행)
  schedule = "45 14 5 5 *" # UTC 기준 14:45 (2025년 5월 5일), 한국 시간으로는 23:45

# 오후 5시 자동 이미지 생성 함수 - 이미지가 없는 급식을 자동으로 생성
[functions.auto-generate-meal-images]
  # 실제 운영 스케줄
  # schedule = "0 8 * * *" # 매일 UTC 8:00 (한국시간 17:00)
  
  # 테스트용 스케줄 (5분 후 실행)
  schedule = "15 15 6 5 *" # UTC 기준 15:15 (2025년 5월 6일), 한국 시간으로는 00:15

# API 경로를 Netlify Functions로 리다이렉트
[[redirects]]
  from = "/api/meals"
  to = "/.netlify/functions/meals"
  status = 200
  force = true
