[build]
  base = "."
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "firebase-admin"]

[functions.generate-meal-image]
  timeout = 60

[functions.verify-meal-image]
  timeout = 60

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify 스케줄된 함수 설정

[functions.auto-generate-meal-images]
  timeout = 60

# API 경로를 Netlify Functions로 리다이렉트
[[redirects]]
  from = "/api/meals"
  to = "/.netlify/functions/meals"
  status = 200
  force = true
