name: 매일 급식 정보 업데이트

on:
  schedule:
    # 매일 오전 10시에 실행 (한국 시간, UTC+9)
    # UTC 기준으로는 오전 1시
    - cron: '0 1 * * *'
  
  # 수동으로도 실행 가능하도록 설정
  workflow_dispatch:

jobs:
  update-meals:
    runs-on: ubuntu-latest
    steps:
      - name: 급식 정보 API 호출
        env:
          API_KEY: ${{ secrets.CRON_API_KEY }}
          NETLIFY_URL: ${{ secrets.NETLIFY_URL }}
        run: |
          echo "급식 정보 업데이트 작업 시작: $(date)"
          curl -X GET "${NETLIFY_URL}/api/cron/meals?api_key=${API_KEY}" \
            -H "Content-Type: application/json" \
            --fail
          echo "급식 정보 업데이트 작업 완료: $(date)"
