name: meal-update

on:
  workflow_dispatch:
  schedule:
    # 오늘 오전 11시 10분에 실행 (한국 시간, UTC+9)
    # UTC 기준으로는 오전 2시 10분
    - cron: '10 2 * * *'

jobs:
  update-meals:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        env:
          API_KEY: ${{ secrets.CRON_API_KEY }}
          NETLIFY_URL: "${{ secrets.NETLIFY_URL || 'https://lunbat.com' }}"
        run: |
          echo "Starting API call"
          curl -v "${NETLIFY_URL}/.netlify/functions/cron-meals?api_key=${API_KEY}" || true
          echo "API call completed"