name: 매일 급식 정보 업데이트

on:
  schedule:
    # 매일 오전 10시에 실행 (한국 시간, UTC+9)
    # UTC 기준으로는 오전 1시
    - cron: '0 1 * * *'
  
  # 수동으로도 실행 가능하도록 설정
  workflow_dispatch:

jobs:
  update-meals:
    runs-on: ubuntu-latest
    steps:
      # 작업 시작
      - name: 급식 정보 업데이트 작업 시작
        run: echo "급식 정보 업데이트 작업 시작: $(date)"
      
      # 네트리파이 API 호출 (오류 무시)
      - name: Netlify API 호출 - 오류 무시
        env:
          API_KEY: ${{ secrets.CRON_API_KEY }}
          NETLIFY_URL: ${{ secrets.NETLIFY_URL || 'https://lunbat.com' }}
        run: |
          echo "급식 업데이트 API 호출"
          
          # 전체 URL 출력
          echo "NETLIFY_URL: ${NETLIFY_URL}"
          
          # curl 명령 실행 (오류 무시)
          curl -v "${NETLIFY_URL}/.netlify/functions/cron-meals?api_key=${API_KEY}" || true
          
          echo "급식 정보 업데이트 작업 완료. 오류가 발생해도 무시하고 작업을 성공으로 처리합니다."
          
          # 성공으로 처리
          exit 0
