name: meal-update

on:
  schedule:
    # 테스트: 오늘 오후 2시 2분에 실행 (한국 시간, UTC+9)
    # UTC 기준으로는 오전 5시 2분
    - cron: '2 5 * * *'
  workflow_dispatch: {}

jobs:
  update-meals:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        env:
          API_KEY: ${{ secrets.CRON_API_KEY }}
          NETLIFY_URL: "${{ secrets.NETLIFY_URL || 'https://lunbat.com' }}"
        run: |
          echo "Starting API call"
          curl -v "${NETLIFY_URL}/api/cron/meals?api_key=${API_KEY}" || true
          echo "API call completed"