name: 매일 급식 정보 업데이트

on:
  schedule:
    # 매일 오전 10시에 실행 (한국 시간, UTC+9)
    # UTC 기준으로는 오전 1시
    - cron: '0 1 * * *'
  
  # 수동으로도 실행 가능하도록 설정
  workflow_dispatch:

jobs:
  update-meals:
    runs-on: ubuntu-latest
    steps:
      - name: 급식 정보 API 호출
        env:
          API_KEY: ${{ secrets.CRON_API_KEY }}
          NETLIFY_URL: ${{ secrets.NETLIFY_URL }}
        run: |
          echo "급식 정보 업데이트 작업 시작: $(date)"
          # 디버깅용 정보 출력 (실제 API 키는 가리고, URL만 확인)
          echo "API 호출 URL: ${NETLIFY_URL}/api/cron/meals"
          
          # API 엔드포인트 상태 확인 (HTTP 상태만 먼저 확인)
          echo "API 엔드포인트 상태 확인:"
          curl -I "${NETLIFY_URL}/api/cron/meals" \
            -H "Content-Type: application/json"
          
          # 실제 API 호출 (상세 오류 정보 표시)
          echo "\n\n실제 API 호출:"
          curl -v -X GET "${NETLIFY_URL}/api/cron/meals?api_key=${API_KEY}" \
            -H "Content-Type: application/json"
          
          echo "\n급식 정보 업데이트 작업 완료: $(date)"
